### ISSUE TITLE
Vim mode compatibility

### ISSUE THREAD

**Issue by n1colassilva** [davisriedel/obsidian-typewriter-mode#39]
Plugin seems to not work when vim mode is toggled on, when in insert mode it works just fine

Apparently the old version this plugin forked had a similar issue, maybe look into  that?

sorry if comment seems a bit weird i'm new to opening issues and contributing to open source lol

**Comment by richiebonilla** [comment]
Thanks for opening this thread @n1colassilva 

@davisriedel , I love this plug-in because it supports `Only maintain typewriter offset when reached` unlike other "typewriter mode" plug-ins. If you could get it working in vim mode, it would be perfect. As noted above, it works as expected in Insert mode, but not in Normal mode. Thank you.

**Comment by davisriedel** [comment]
I just published a (possible) fix for this. The problem was, that the VIM plugin triggers a "scroll" event after each movement in normal mode, which prevents this plugin from running. I added a check to ignore this event. I got it to work on my machine.

I released this fix as version 0.0.3-beta.1 which you can install using the BRAT plugin (as described in the README). Feel free to check it out and tell me if it works for you.
