### ISSUE TITLE
[Bug] Problem with the New Table Editor in Obsidian 1.5 

### ISSUE THREAD

**Issue by Drakemoor** [davisriedel/obsidian-typewriter-mode#42]
Obsidian 1.5 introduced a new table editor. 

When in Live Preview and trying to edit text inside a table, the text is always moved to the top of the screen. If one edits the text inside a table in Source Mode, the Typewriter Mode Plugin behaves as expected. 

![Animation](https://github.com/davisriedel/obsidian-typewriter-mode/assets/93224920/a0bee334-b78f-496e-b7b4-b76f7d9de6ed)

**Comment by davisriedel** [comment]
The problem was: Obsidian regards each table cell as a standalone editor. This means that we are getting the scroll position of the table cell and not the editor itself. To fix this issue I had to rewrite quite a lot: Now we always try to get the root editor and use it for calculations. This seems to work in my quick tests.

I released this fix as version 0.0.4-beta.1 which you can install using the BRAT plugin (as described in the README). Feel free to check it out and please give me feedback if it works for you.

I hope that although I had to do many changes, these don't have other unforseen side-effects. If you find any other bug, please open a new issue. Thanks a lot!
