### ISSUE TITLE
Line highlighting not rendering in light mode

### ISSUE THREAD

**Issue by seldstein** [davisriedel/obsidian-typewriter-mode#43]
Hey Davis, love the plugin! I'm having a weird issue with the line highlighting. In dark mode it works fine, but in light mode, the text is highlighted instead of its background.

<img width="981" alt="Screenshot 2024-01-09 at 11 01 09 AM" src="https://github.com/davisriedel/obsidian-typewriter-mode/assets/106436328/9b5f482d-5d7a-4975-aad0-21d8963fb662">
<img width="949" alt="Screenshot 2024-01-09 at 11 01 21 AM" src="https://github.com/davisriedel/obsidian-typewriter-mode/assets/106436328/2d8d4917-e389-4f4c-805a-d7b8a22875ea">

I have a 2023 Macbook and I'm using the Minimal Theme. I can show you my settings files if you think there might be a conflict there. Let me know if there's any other info that might be helpful. Thanks!

**Comment by davisriedel** [comment]
Thanks for opening the issue.

Previously the current line highlight was rendered above the editor and `mix-blend-mode: screen` was used to make it appear as if it was underneath the text. I did it this way, because the editor components itself each have the background color set by obsidian (not only the actual editor background), and I am not sure, if making all of those transparent interferes with any obsidian feature or other plugin.

Turns out `mix-blend-mode: screen` doesn't behave well depending on the background color and the chosen color for the current line highlight. I now opted for actually placing the line behind the text and making the editor components transparent. I released this as version 0.0.4-beta.2 which you can install with BRAT. Please report back if you experience any interference with other plugins.

I now also implemented the option to chose two different colors for the current line highlight for dark and light themes.

**Comment by seldstein** [comment]
Thanks for the explanation. Seems to be working well! I'll let you know if I run into any more issues.

**Comment by acook** [comment]
The `screen` mix strategy only lightens colors. What you might do instead is specify `screen` for the light theme and `multiply` for the dark theme.
