### ISSUE TITLE
Cannot access command palette from fullscreen

### ISSUE THREAD

**Issue by seldstein** [davisriedel/obsidian-typewriter-mode#44]
Hi Davis,

I can't access the command palette from fullscreen mode. Let me know if there's other info you need that would help solve this. Thanks!

Also: I was trying to access the palette because I wanted to split the screen to see two notes at once. I left fullscreen mode, split the screen, and reactivated fullscreen. One of the notes closed. So it seems that you can't split the screen in fullscreen mode. Let me know if you'd like me to open a separate issue thread for this. Thanks again!

**Comment by davisriedel** [comment]
Hey, thanks for opening the issue. To achieve Fullscreen Mode I am just calling `requestFullscreen` on the Editor element. Since Obsidian places the command palette on a completely separate div that is not a child of the editor element, there is no way to make it appear in fullscreen mode as it is implemented at the moment. This also explains why you can only fullscreen one editor, as only one element can be fullscreen.

To solve these issues we'd have to fullscreen the complete obsidian window and do some css tricks to make the editor appear fullscreen. I tried some things, but somehow `position: fixed` on the editor is not working. I suppose obsidian is using one of these properties [https://stackoverflow.com/a/52937920](https://stackoverflow.com/a/52937920) in any of the parent nodes. But I could not identifiy it quickly.

So fixing this requires some more thought and experimentation. I have thus postponed it to a later release.

**Comment by seldstein** [comment]
Gotcha. Thanks for the explanation. For now, I'm using fullscreen with the Minimal theme and Hider plugin. That's what I was doing before, and it works fine.

**Comment by davisriedel** [comment]
Hey 👋 in the mean time I have completely rewritten the fullscreen mode, which fixes this issue as well. If any problems remain, feel free to open an issue.
