### ISSUE TITLE
«Only activate after first interaction» not really working

### ISSUE THREAD

**Issue by jerrygreen** [davisriedel/obsidian-typewriter-mode#46]
## The issue

When I open a file, Obsidian takes focus of the note automatically, and «Typewriter Mode» does instantly dim my other lines.

## What I expected

Despite automatic focus, «Typewriter Mode» shouldn't dim other lines until I do any action, like inputting characters or selecting other characters or lines. Therefore, when I click through my files – all my notes should be visible as normal. Until I manually touch them.

## More thought

My guess is that someday in the past Obsidian didn't focus the note right-away, so plugin worked as expected. But I just started using Obsidian now and a selected note get instantly focused – which is actually convenient, and I don't want to disable it. Probably a new feature or idk. Whether it is, I want «Only activate after first interaction» feature work properly, taking into consideration the auto-selection – it shouldn't count as an actual interaction, from this feature's point of view.

**Comment by davisriedel** [comment]
Thanks for opening the issue. Turns out, this bug was introduced while fixing a bug in the last version. Many CSS classes used by the plugin were moved from the editor element to the body. So was the `ptm-first-open` class that indicates if an initial interaction has happened. This broke the code because like `ptm-select` and `ptm-wheel`, that are used to disable dimming when selecting / scrolling, `ptm-first-open` needs to be added to the editor directly, for the code to work. I moved the class back to the editor element, and it works as before again. Sorry for the inconvenience.

I published this fix as `0.0.6-beta.1`, which you can install using the BRAT plugin (as described in the `README`). I am planning to release `0.0.6` officially soon. Please feel free to report back, if it works in the beta for you.
