### ISSUE TITLE
[Request] Let dropdown menu appear while writing in typewriter focus mode

### ISSUE THREAD

**Issue by ulahcherubim** [davisriedel/obsidian-typewriter-mode#62]
Simple request as per the title: Let dropdown menu appear while writing in typewriter focus mode

**Comment by davisriedel** [comment]
Unfortunately, this is not as easy as it seems. For fullscreen mode, we are just using the JS function to make a DOM element fullscreen. Since obsidian does not put overlays on the editor element itself but instead on a sibling element, those are not visible. We would need to completely rewrite fullscreen mode to use some other way of displaying the editor fullscreen.

**Comment by davisriedel** [comment]
I have completely rewritten the fullscreen mode in the latest version. This should fix this issue as well. If not, please don't hesitate to reopen this issue.
