### ISSUE TITLE
Full Screen Mode

### ISSUE THREAD

**Issue by AhmedThahir** [davisriedel/obsidian-typewriter-mode#79]
I believe this is similar to #64 

## Steps

1. Toggle focus mode using Cmd-l (my shortcut)
2. Use Command palette using Cmd-p (default shortcut)
3. Click escape

## Expected behavior
Focus mode remains as-is, command palette exits

## Actual behavior
Focus mode exits, command palette remains as-is

https://github.com/user-attachments/assets/469965cd-5e79-4618-a3d5-4a1c676e9379

This is very annoying to use.

## Specs

- Obsidian: Version 1.6.7
- Macbook Air M3

Please let me know if there is any setting to solve this.

**Comment by davisriedel** [comment]
This is fixed in the latest commit. I was using the JS `requestFullscreen` Function, which automatically listens to `ESC` being pressed and thus prevents Obsidian from listening to ESC. The workaround is to use electron's API directly to request full-screen instead of using the browser API. This means that `ESC` no longer exits the writing focus mode. It is closed if exiting fullscreen with your OS's capabilities or when using the toggle command again.

**Comment by AhmedThahir** [comment]
Now works as expected. Thanks a lot!

**Comment by AhmedThahir** [comment]
Hi @davisriedel 
In the current version, when I click `Cmd +`, the full screen mode exits.

This was not the case before.

**Comment by AhmedThahir** [comment]
Any updates?
