### ISSUE TITLE
Highlight position is off

### ISSUE THREAD

**Issue by Fred-Vatin** [davisriedel/obsidian-typewriter-mode#80]
Obsidian   | OS                           | typewriter
---------- | ---------------------------- | ---- 
1.6.7      | Win 10 x64 pro 22H2 | 0.0.11

Tested on a sandbox vault, with default plugin settings. On paragraphs, you can see the highlight should be a little lower.
![image](https://github.com/user-attachments/assets/0f805747-2ce1-494d-b0d2-bc7043d79170)

Same and worse on list items.
![image](https://github.com/user-attachments/assets/0674abf8-3b96-4205-8dc8-ad918fb628dd)

On titles, it is more aligned with line number than text. The problem relies also on default theme that misaligns title and line number.
![image](https://github.com/user-attachments/assets/fe4712bb-5eee-4fb2-b07e-14482ba68733)

Of course, this can vary according to theme and other custom CSS modifications. That’s why I suggest to add classes so users can apply their own CSS style to customize highlight position and other properties.

**Comment by davisriedel** [comment]
Thank you for opening the issue. The line highlight was indeed off depending on the font you used. This should be fixed in the latest commit. I rewrote how the line position is calculated. This should also improve the performance. I will release it in a new version soon.

Regarding CSS: The line already has a CSS class: `ptm-current-line-highlight`. You should be able to add custom CSS snippets modifying the current line highlight using this class.
