### ISSUE TITLE
"Failed to load plugin typewriter-mode" when installing v0.0.12 on Obsidian iOS

### ISSUE THREAD

**Issue by bmndc** [davisriedel/obsidian-typewriter-mode#81]
Previous versions up to 0.0.11 works fine.

Will add more information here as soon as I can find how to debug the app.

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/94e6fce2-ca3b-45c3-902a-fe89c5176ebf">

Obsidian iOS: 1.6.7
Device: iPad Pro 11 (2nd generation), iOS 18.1b5

```
SYSTEM INFO:
	Operating system: ios 18.1 (Apple iPad8,9)
	Obsidian version: 1.6.7 (149)
	API version: v1.6.7
	Login status: not logged in
	Live preview: on
	Base theme: adapt to system
	Community theme: Tokyo Night v0.4.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 0
```

**Comment by davisriedel** [comment]
Thank you for reporting this issue. The problem resulted from the rewrite of the writing focus because it is now importing the native electron API that is not available on mobile. The plugin now checks if native APIs are available first and imports them dynamically. I will release a new version soon.
